import Head from 'next/head'
import Addblog from '../../components/Addblog'
import { useRouter } from 'next/router'

export default function AddBlog() {
    const router = useRouter()
    const addBlogHandler = async (data) => {
        const response = await fetch("/api/new-blog", {
            method: "POST",
            body: JSON.stringify(data),
            headers: {
                "Content-Type": "application/json"
            }
        });
        const reponseData = await response.json()
        console.log(reponseData);
    };
return (
    <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Addblog addBlogHandler={addBlogHandler}/>
    </div>
)
}